// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5thQDR7k92gPVLOU5R_U6t0C8w5WB55Q',
    appId: '1:874185747731:web:9a548e8e0b238925f4bee6',
    messagingSenderId: '874185747731',
    projectId: 'bolu-c9050',
    authDomain: 'bolu-c9050.firebaseapp.com',
    storageBucket: 'bolu-c9050.appspot.com',
    measurementId: 'G-8CV5RL9D0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiAGc256Oun-bcANyIGkoqYLRiCWiaiLs',
    appId: '1:874185747731:android:a77dd5365b51474bf4bee6',
    messagingSenderId: '874185747731',
    projectId: 'bolu-c9050',
    storageBucket: 'bolu-c9050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyp7y7c1B5Wsr3BGE3FAy30rjAac3OZBc',
    appId: '1:874185747731:ios:750b211f27f658fbf4bee6',
    messagingSenderId: '874185747731',
    projectId: 'bolu-c9050',
    storageBucket: 'bolu-c9050.appspot.com',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyp7y7c1B5Wsr3BGE3FAy30rjAac3OZBc',
    appId: '1:874185747731:ios:e0c01b3b135299e3f4bee6',
    messagingSenderId: '874185747731',
    projectId: 'bolu-c9050',
    storageBucket: 'bolu-c9050.appspot.com',
    iosBundleId: 'com.example.hotelBooking.RunnerTests',
  );
}
